project:
  type: book
  output-dir: _site

book:
  title: "The Human Brain"
  author: "Gregory McCarthy"
  date: today
  chapters:
    - index.qmd
    - chapters/chapter01/why-brains.qmd
    - chapters/chapter02/metaphors.qmd

format:
  html:
    theme: journal
    toc: true
    number-sections: true