project:
  type: book
  output-dir: _site

book:
  title: "Human Brain Neuroscience"
  author: "Gregory McCarthy"
  date: today
  chapters:
    - index.qmd
    - chapters/chapter02/Levels of Explanation and Brain Metaphors.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true