project:
  type: book
  output-dir: _site

book:
  title: "The Human Brain"
  author: "Gregory McCarthy"
  date: today
  sidebar: true
  search: true
  chapters:
    - index.qmd
    - chapters/chapter02/Levels of Explanation and Brain Metaphors.qmd
    # Add more chapters as you create them:
    # - chapters/chapter03/your-next-chapter.qmd
    # - chapters/chapter04/another-chapter.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true